name: bloc_implementation
description: The bloc implementation of the Toda App
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  apis:
    path: ../common/apis
  bloc: ^8.1.2
  cloud_firestore: ^4.8.4
  collection: ^1.17.1
  core:
    path: ../common/core
  device_info_plus: ^9.0.3
  equatable: ^2.0.5
  firebase_auth: ^4.7.2
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_localizations:
    sdk: flutter
  freezed: ^2.4.1
  freezed_annotation: ^2.4.1
  google_sign_in: ^6.1.4
  hydrated_bloc: ^9.1.2
  internet_connection_checker_plus: ^2.0.0
  intl: ^0.18.0
  json_annotation: ^4.8.1
  moment_dart: ^1.0.1
  realm: ^1.3.0
  repositories:
    path: ../common/repositories

dev_dependencies:
  bloc_test: ^9.1.2
  build_runner: ^2.3.3
  fake_cloud_firestore: ^2.4.1+1
  flutter_test:
    sdk: flutter
  json_serializable: ^6.7.1
  mocktail: ^1.0.0
  very_good_analysis: ^5.0.0

flutter:
  uses-material-design: true
  generate: true