name: repositories
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  apis:
    path: ../apis
  collection: ^1.17.1
  firebase_auth: ^4.7.2
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  google_sign_in: ^6.1.4
  internet_connection_checker_plus: ^2.0.0
  intl: ^0.18.0
  json_annotation: ^4.8.1
  # make this only used in apis package
  realm: ^1.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.0
  very_good_analysis: ^5.0.0
